### ISSUE TITLE
PhpStorm code completion not working.

### ISSUE THREAD

**Issue by fdrobidoux** [Garethp/ScreepsAutocomplete#15]
I made a test file to test the behavior of the autocomplete, and it's clearly not working.

[See here.](http://prntscr.com/a1zavo)

Plus, the autocomplete itself does not work with any of the objects when using `Only type-based completion` option in `File > Settings > Languages & Frameworks > JavaScript`.

I have no idea how this was working in WebStorm for you. I have spent 2 full days trying to make it work. Any ideas?

**Comment by Zinal001** [comment]
Well, it works for me on both WebStorm and an older version of PhpStorm (10.0.1)
Did you turn the project into a library? `File > Settings > Languages & Frameworks > JavaScript > Libraries > Add...`

[See here](https://drive.google.com/file/d/0B7o2XcErnOs2X3FueXhkRFJBNGM/view?usp=sharing)

I'm honestly not sure why it's not working for you.. What version of PhpStorm do you use?

**Comment by fdrobidoux** [comment]
...It can't be because I'm using an Early-Access Public build, right?

**Comment by fdrobidoux** [comment]
Yup, it really was because I was using a test version.

**Comment by Garethp** [comment]
Thanks for the heads up :+1: When the EAP is more fleshed out later, I'll give it a test again to make sure it's working in later builds
