### ISSUE TITLE
MoveTo overload missing

### ISSUE THREAD

**Issue by Tim-Pohlmann** [Garethp/ScreepsAutocomplete#25]
http://support.screeps.com/hc/en-us/articles/203013212-Creep#moveTo

the second overload seems to be missing which causes Webstorm to flag all my moveTo calls for having the wrong number of arguments.

**Comment by Zinal001** [comment]
The reason for this is because JSDoc's doesn't know about overloaded methods..
It's not possible to have 2 different signatures in one class. For example, you cannot specify the moveTo(x, y, [opts]) method and then the moveTo(target, [opts]) after it, that will cause an error as well.

**Comment by Garethp** [comment]
Hm... maybe an option would be to mark `y` and `[opts]` as optional?

**Comment by Zinal001** [comment]
That could work.. I'll try to do that when I get home and see how my editor handles it.

**Comment by Garethp** [comment]
Cool. If you don't find the time, I'll take a look tonight myself

**Comment by Garethp** [comment]
@Zinal001 has merged in what should be a fix. Can you confirm that this issue is closed? @thPion
