### ISSUE TITLE
Issue with creep.moveTo() in WebStorm

### ISSUE THREAD

**Issue by AidaPaul** [Garethp/ScreepsAutocomplete#29]
Hi there!

It seems that WebStorm doesn't correctly detect the moveTo() defintion for creep instance. I've tried the following forms:

```
creep.moveTo(sources[0], {reusePath: cache});
creep.moveTo(targets[0]);
creep.moveTo(12,114);
creep.moveTo(12,114,{});
```

For all of them WebStorm will highlights the `moveTo` with explanation: `Unresolved function or method moveTo()`. Here is a full code sample:

```
var roleTest = {

    /** @param {Creep} creep **/
    run: function(creep) {
        creep.moveTo(sources[0], {reusePath: cache});
        creep.moveTo(targets[0]);
        creep.moveTo(12,114);
        creep.moveTo(12,114,{});
    }
};

module.exports = roleTest;
```

Any help would be highly appreciated!

**Comment by Garethp** [comment]
Try changing it to

``` js
var roleTest = {

    /** @param creep Creep **/
    run: function(creep) {
        creep.moveTo(sources[0], {reusePath: cache});
        creep.moveTo(targets[0]);
        creep.moveTo(12,114);
        creep.moveTo(12,114,{});
    }
};

module.exports = roleTest;
```

**Comment by AidaPaul** [comment]
That did the trick, thanks! 
This template with uppercase Creep is what you get from doing the tutorial, and I imagine that other folk will build on top of it too. I am not well versed with js, but how feasible would it be to capture both cases?

**Comment by Zinal001** [comment]
... I don't understand this ...
WebStorm should be able to handle both the `/** @param {Creep} creep **/` and the `/** @param creep Creep **/` lines... I wonder why the second line works but not the first since the official JSDoc implementation uses the first line format (Where the class is first and surrounded by { }).

If you don't mind me asking.. What version of Webstorm are you using?

**Comment by AidaPaul** [comment]
@Zinal001 not a problem at all! It seems to be the latest: `WebStorm 2016.2
Build #WS-162.1121.31, built on July 9, 2016.`

From quick look the forms that work: 

```
/** @param {Creep} Creep **/
/** @param {creep} Creep **/
/** @param creep Creep **/
/** @param Creep creep **/
/** @param Creep Creep **/
```

But the following don't:

```
/** @param {creep} creep **/
/** @param {Creep} creep **/
```

Hope that helps.

**Comment by Garethp** [comment]
Weird, but good to know
