### ISSUE TITLE
[Feature Request] Atom.io Support

### ISSUE THREAD

**Issue by fipso** [Garethp/ScreepsAutocomplete#36]
Would really like to use this in Atom.io.
Maybe someone can port this.

**Comment by Garethp** [comment]
I'll investigate in to how to get the two working together

**Comment by Garethp** [comment]
I'll update the documentation soon, but I've got it to work with the following:
- Copy `ScreepsAutocomplete` in to your project
- Install the `atom-ternjs` plugin
- Add the following as your `.tern-project` file

``` json
{
  "ecmaVersion": 6,
  "libs": [],
  "loadEagerly": [
    "ScreepsAutocomplete/**/*.js"
  ]
}
```
- Enjoy

**Comment by Garethp** [comment]
Added to `README.md`
