### ISSUE TITLE
Creep.moveTo in WebStorm

### ISSUE THREAD

**Issue by benjaminderei** [Garethp/ScreepsAutocomplete#40]
Hi,

the method moveTo of Creep is not recognize by webstorm when used in a function with:
/*\* @param {Creep} creep **/
declared at top ...
any solution ?

**Comment by Garethp** [comment]
Hi, someone found this before. Take a look at [this issue](https://github.com/Garethp/ScreepsAutocomplete/issues/29), see if it works for you
