### ISSUE TITLE
IntelliJ Universal 2016.2.5 - filter: (structure) is not resolving correctly

### ISSUE THREAD

**Issue by MichaelCowanPdx** [Garethp/ScreepsAutocomplete#55]
This code works correctly in Screeps, no issues (and I got it from one of their examples)

Intellisense hover over underlined word 'structure':
Unresolved variable or structure

Code Analysis Tool:
Argument type boolean is not assignable to parameter type {filter>:(Object|Function|string)}

![image](https://cloud.githubusercontent.com/assets/16511947/20454255/02d12490-adf0-11e6-8aa2-89ec61aed3ea.png)

**Comment by MichaelCowanPdx** [comment]
Ah. This was an issue with IntelliJ Javascript language level. I set it up to 6 and this was resolved.

Not an issue

**Comment by Garethp** [comment]
Thanks for that. I was rather confused myself
