### ISSUE TITLE
Sublime Text 3, SublimeCodeIntel Issue

### ISSUE THREAD

**Issue by parkour86** [Garethp/ScreepsAutocomplete#68]
I placed the ScreepsAutocomplete directory into my projects folder but it doesn't seem to work. When I move the files from the ScreepsAutocomplete folder into my projects folder it works just fine. I don't like having all the Screeps autocomplete files in the same directory as my screeps code. Is there a configuration in the package settings I can change to have it read from the ScreepsAutocomplete directory?

**Comment by OJBridger** [comment]
I also have this problem, have to have all of the files in the same directory as my Screeps main.js file. Which is very messy and also means I can't push it to my github Screeps repository because it clashes with the Garethp repository

**Comment by IBotDEU** [comment]
Just go into Preferences > Package Settings > SublimeCodeIntel > Settings -- User
again and change this line:
"codeintel_scan_extra_dir": [],
into this:
"codeintel_scan_extra_dir": ["/ScreepsAutocomplete"],
